### ISSUE TITLE
#VVB-5: Routing

### ISSUE THREAD

**Issue by ikwebdev** [SalamanderSunburn/VVBook#5]
- [x] Redirection of non-authorized users to the _Sign In_ page
- [ ] Redirection of authorized users to the _Vacations _page

**Comment by VikiRyn** [comment]
" Redirection of non-authorized users to the _Vacations _page"
I think redirect to the _Vacations _page should be for **authorized** *users

**Comment by SalamanderSunburn** [comment]
@VikiRyn, my fault. Bad copy/paste ) That was really for authorized users
